# Clean and don't fail
install:
  - rm -rf docs/* || exit 0
  - git submodule init
  - git submodule update
  - chmod 777 ./bin/hugo

# Build the website
script:
  - ./bin/hugo -d docs
  - sed -i 's/href="\//href="/g' docs/index.html && sed -i 's/src="\//src="/g' docs/index.html && sed -i 's/url("\//url("..\//g' docs/css/main.css

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
